<a href="https://colab.research.google.com/github/Perine23Dev/analyse-entreprises-emploi-republique-du-congo/blob/feature%2Fexploration-donnees/exploration_membre4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import userdata

try:
    token = userdata.get('GITHUB_TOKEN')
    if token:
        print(f"Le secret 'GITHUB_TOKEN' a été récupéré avec succès. (début: {token[:5]}...)")
    else:
        print("Le secret 'GITHUB_TOKEN' existe mais est vide.")
except Exception as e:
    print(f"Erreur lors de la récupération du secret 'GITHUB_TOKEN': {e}")

Le secret 'GITHUB_TOKEN' a été récupéré avec succès. (début: bchri...)

In [ ]:
from google.colab import userdata
token = userdata.get('GITHUB_TOKEN')

!git clone https://bchristroslant-byte:{token}@github.com/Perine23Dev/analyse-entreprises-emploi-republique-du-congo.git

Cloning into 'analyse-entreprises-emploi-republique-du-congo'...
remote: Enumerating objects: 7, done.
remote: Counting objects: 100% (7/7), done.
remote: Compressing objects: 100% (7/7), done.
remote: Total 7 (delta 0), reused 0 (delta 0), pack-reused 0 (from 0)
Receiving objects: 100% (7/7), 5.19 KiB | 5.19 MiB/s, done.

In [ ]:
%cd analyse-entreprises-emploi-republique-du-congo

/content/analyse-entreprises-emploi-republique-du-congo

In [ ]:
!git config user.name "bchristroslant-byte"
!git config user.email "bchristroslant@email.com"

In [ ]:
# Voir les branches existantes
!git branch -a

* main
  remotes/origin/HEAD -> origin/main
  remotes/origin/feature/analyse-pandas
  remotes/origin/feature/analyse-sql
  remotes/origin/feature/exploration-donnees
  remotes/origin/feature/nettoyage-donnees
  remotes/origin/feature/visualisations
  remotes/origin/main

In [ ]:
!git checkout -b exploration-donnees origin/feature/exploration-donnees

branch 'exploration-donnees' set up to track 'origin/feature/exploration-donnees'.
Switched to a new branch 'exploration-donnees'

In [ ]:
# Créer une nouvelle sous-branche 'exploration_membre4' à partir de 'exploration-donnees'
!git checkout -b exploration_membre4

Switched to a new branch 'exploration_membre4'

In [ ]:
# Sauvegarder le DataFrame 'df' dans un fichier CSV dans le répertoire du dépôt
# Assurez-vous que le chemin est correct et que vous êtes bien dans le répertoire du dépôt.
# Le nom du fichier sera df_exploration_membre4.xlxs
df.to_csv('df_exploration_membre4.xlsx', index=False)

In [ ]:
# Ajouter le nouveau fichier au staging area de Git
!git add df_exploration_membre4.xlsx

In [ ]:
# Commiter les changements
!git commit -m "Ajout du DataFrame df sur la branche exploration_membre4"

[exploration_membre4 e4d79e2] Ajout du DataFrame df sur la branche exploration_membre4
 1 file changed, 18818 insertions(+)
 create mode 100644 df_exploration_membre4.xlsx

In [ ]:
# Pousser la nouvelle branche vers le dépôt distant
# L'option -u (ou --set-upstream) configure la branche locale pour suivre la branche distante du même nom.
!git push -u origin exploration_membre4

remote: Invalid username or token. Password authentication is not supported for Git operations.
fatal: Authentication failed for 'https://github.com/Perine23Dev/analyse-entreprises-emploi-republique-du-congo.git/'

In [ ]:
from google.colab import userdata
token = userdata.get('GITHUB_TOKEN')

# Configure Git pour utiliser le token pour l'authentification
# Mettre à jour l'URL du dépôt distant pour inclure le token
!git remote set-url origin https://oauth2:{token}@github.com/Perine23Dev/analyse-entreprises-emploi-republique-du-congo.git

# Re-exécuter la commande push après avoir mis à jour l'URL distante
!git push -u origin exploration_membre4

remote: Invalid username or token. Password authentication is not supported for Git operations.
fatal: Authentication failed for 'https://github.com/Perine23Dev/analyse-entreprises-emploi-republique-du-congo.git/'

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
import pandas as pd

chemin = '/content/drive/MyDrive/Groupe_3 Akieni/Dataset/Entreprise_congo.xlsx'

df = pd.read_excel(chemin)

/usr/local/lib/python3.13/dist-packages/openpyxl/worksheet/_reader.py:329: UserWarning: Unknown extension is not supported and will be removed
  warn(msg)

In [ ]:
!pip install openpyxl

Requirement already satisfied: openpyxl in /usr/local/lib/python3.13/dist-packages (3.1.5)
Requirement already satisfied: et-xmlfile in /usr/local/lib/python3.13/dist-packages (from openpyxl) (2.0.0)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18787 entries, 0 to 18786
Data columns (total 20 columns):
 #   Column                                     Non-Null Count  Dtype
---  ------                                     --------------  -----
 0   Année création                             18787 non-null  int64
 1   Département                                18787 non-null  object
 2   Raison sociale établissement principal     18787 non-null  object
 3   Activité déclarée                          18777 non-null  object
 4   Activité au sens de la nomenclature OHADA  18683 non-null  object
 5   Forme juridique                            18787 non-null  object
 6   Statut juridique                           18787 non-null  object
 7   Catégorie                                  5545 non-null   object
 8   Genre                                      18675 non-null  object
 9   Age                                        18455 non-null  float64
 10  Nationalité                                18339 non-null  object
 11  Branche                                    18761 non-null  object
 12  Secteur                                    18769 non-null  object
 13  capital                                    16755 non-null  object
 14  part_capital_etranger                      17136 non-null  float64
 15  salarie                                    18784 non-null  float64
 16  nbre_empl_congolais                        18724 non-null  float64
 17  chiffre_aff_mo_annuel                      18787 non-null  object
 18  chiffre_aff_mo_annuel_1                    18787 non-null  int64
 19  chiffre_aff_mo_annuel_2                    18787 non-null  float64
dtypes: float64(5), int64(2), object(13)
memory usage: 2.9+ MB

In [ ]:
cols = df.columns[-5:]

cols_to_convert_map = {
    cols[0]: 'Int64', # 'capital'
    cols[1]: 'Int64', # 'part_capital_etranger'
    cols[2]: 'float64', # 'salarie'
    cols[3]: 'float64', # 'nbre_empl_congolais'
    cols[4]: 'float64' # 'chiffre_aff_mo_annuel'
}

# Identify columns that are 'object' type and need cleaning before conversion
# Based on df.info(), 'capital' and 'chiffre_aff_mo_annuel' are likely candidates.
object_cols_in_map = [col for col, dtype in cols_to_convert_map.items() if df[col].dtype == 'object']

for col_name in object_cols_in_map:
    # Ensure the column is treated as string before applying string methods
    # Then remove spaces and replace commas with dots
    df[col_name] = df[col_name].astype(str).str.replace(' ', '', regex=False)
    df[col_name] = df[col_name].str.replace(',', '.', regex=False)
    # Convert to numeric, coercing errors to NaN
    df[col_name] = pd.to_numeric(df[col_name], errors='coerce')

# Now apply the final astype conversion, which will work with cleaned and numeric-like data
df = df.astype(cols_to_convert_map)

In [ ]:
print(df.dtypes.tail(5))

df.to_excel('/content/drive/MyDrive/Groupe_3 Akieni/Dataset/ma_base_modifiee.xlsx', index=False)

salarie                      Int64
nbre_empl_congolais          Int64
chiffre_aff_mo_annuel      float64
chiffre_aff_mo_annuel_1    float64
chiffre_aff_mo_annuel_2    float64
dtype: object

In [ ]:
df['Catégorie']

0        TPE-PE
1           TPE
2        TPE-PE
3        TPE-PE
4           TPE
          ...
18782       NaN
18783       NaN
18784       NaN
18785       NaN
18786       NaN
Name: Catégorie, Length: 18787, dtype: object

In [ ]:
display(df.columns)

Index(['Année création', 'Département',
       'Raison sociale établissement principal', 'Activité déclarée',
       'Activité au sens de la nomenclature OHADA', 'Forme juridique',
       'Statut juridique', 'Catégorie', 'Genre', 'Age', 'Nationalité',
       'Branche', 'Secteur', 'capital', 'part_capital_etranger', 'salarie',
       'nbre_empl_congolais', 'chiffre_aff_mo_annuel',
       'chiffre_aff_mo_annuel_1', 'chiffre_aff_mo_annuel_2'],
      dtype='object')

In [ ]:
df[['Statut juridique', 'Catégorie']]

              Statut juridique Catégorie
0      Entreprise individuelle    TPE-PE
1      Entreprise individuelle       TPE
2         Société de personnes    TPE-PE
3      Entreprise individuelle    TPE-PE
4      Entreprise individuelle       TPE
...                        ...       ...
18782     Société de personnes       NaN
18783     Société de personnes       NaN
18784     Société de personnes       NaN
18785      Société de capitaux       NaN
18786      Société de capitaux       NaN

[18787 rows x 2 columns]

In [ ]:
df = df.dropna(how='all')

In [ ]:
df = df.drop_duplicates()

In [ ]:
df = df.reset_index(drop=True)

In [ ]:
print(df.shape)

(18787, 20)

In [ ]:
df[:5544]

,Année création,Département,Raison sociale établissement principal,Activité déclarée,Activité au sens de la nomenclature OHADA,Forme juridique,Statut juridique,Catégorie,Genre,Age,Nationalité,Branche,Secteur,capital,part_capital_etranger,salarie,nbre_empl_congolais,chiffre_aff_mo_annuel,chiffre_aff_mo_annuel_1,chiffre_aff_mo_annuel_2
0,2023,Pointe-Noire,EL SHADDAI,MERCERIE,Commerce de détail en magasin spécialisé de te...,EI,Entreprise individuelle,TPE-PE,Femme,45.0,Congolaise,Commerce,Tertiaire,500000,0.0,1,1,1000000.0,1500000.0,2000000.0
1,2023,Niari,BADJEL,Commerce de détail en magasin spécialisé des p...,Commerce de détail en magasin spécialisé des p...,EI,Entreprise individuelle,TPE,Homme,49.0,Mauritanienne,Commerce,Tertiaire,NaN,NaN,1,0,1500000.0,2000000.0,2500000.0
2,2015,Pointe-Noire,HIRAM SERVICES,MISE A DISPOSITION DE PERSONNEL,activités liées aux ressources humaines,SARLU,Société de personnes,TPE-PE,Homme,43.0,Congolaise,Services aux entreprises,Tertiaire,0,0.0,1,1,0.0,0.0,0.0
3,2015,Pointe-Noire,HB,VENTE D'ELECTROMENAGER,commerce de détail en magasin spécialisé d’art...,EI,Entreprise individuelle,TPE-PE,Homme,40.0,Malienne,Commerce,Tertiaire,0,0.0,4,0,0.0,0.0,0.0
4,2026,Niari,BADJEL,Commerce de détail en magasin spécialisé de pr...,Commerce de détail en magasin spécialisé de pr...,EI,Entreprise individuelle,TPE,Homme,49.0,Mauritanienne,Commerce,Tertiaire,NaN,NaN,1,0,1500000.0,2000000.0,2500000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5539,2024,Brazzaville,S.C. ATLANTIC,COMMERCE DE DÉTAIL EN MAGASIN SPÉCIALISÉ D'ART...,commerce de détail en magasin spécialisé d'art...,EI,Entreprise individuelle,NaN,Homme,46.0,Congolaise,Commerce,Tertiaire,NaN,0.0,1,1,24000000.0,24000000.0,24000000.0
5540,2024,Brazzaville,IMMEUBLE LOCATION OPEN,ACTIVITÉS DES AGENCES IMMOBILIÈRES,activités des agences immobilières,SARLU,Société de personnes,NaN,Homme,30.0,Congolaise,Activités immobilières,Tertiaire,1000000,0.0,1,1,30000000.0,30000000.0,30000000.0
5541,2024,Brazzaville,CLASSE ROYAL,COMMERCE DE DÉTAIL EN MAGASIN SPÉCIALISÉ DE TE...,commerce de détail en magasin spécialisé des p...,EI,Entreprise individuelle,NaN,Homme,38.0,Congolaise,Commerce,Tertiaire,0,0.0,1,1,8000000.0,9000000.0,9000000.0
5542,2024,Brazzaville,LEADER SYSTEM TECHNOLOGY,COMMERCE DE DÉTAIL EN MAGASIN SPÉCIALISÉ D'ÉQU...,commerce de détail en magasin spécialisé d'équ...,SARL,Société de personnes,NaN,Homme,44.0,Malienne,Commerce,Tertiaire,1000000,0.0,2,0,50000000.0,100000000.0,150000000.0
5543,2024,Brazzaville,OBS GROUP,commerce de véhicules automobiles,commerce de véhicules automobiles,SARLU,Société de personnes,NaN,Homme,28.0,Malienne,Commerce,Tertiaire,1000000,0.0,2,0,26000000.0,50000000.0,100000000.0